"""drop batches, add quantity unit_cost expiry_date to items, movements references items

Revision ID: 0038f210c3c3
Revises: 5264eacdc261
Create Date: 2026-05-16 21:16:35.258597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0038f210c3c3'
down_revision: Union[str, Sequence[str], None] = '5264eacdc261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the new items columns first.
    op.add_column('items', sa.Column('quantity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('items', sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('items', sa.Column('expiry_date', sa.Date(), nullable=True))

    # Rewire stock_movements: batch_id -> item_id. Empty seed means no rows to
    # migrate; we just need to drop the old FK + column and add the new one.
    op.drop_constraint(op.f('stock_movements_batch_id_fkey'), 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_batch_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'batch_id')
    op.add_column('stock_movements', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f('stock_movements_item_id_fkey'),
        'stock_movements', 'items', ['item_id'], ['id'], ondelete='RESTRICT',
    )
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)

    # Now batches has no inbound references — safe to drop.
    op.drop_index(op.f('ix_batches_batch_code'), table_name='batches')
    op.drop_index(op.f('ix_batches_item_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_location_id'), table_name='batches')
    op.drop_table('batches')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.create_foreign_key(op.f('stock_movements_batch_id_fkey'), 'stock_movements', 'batches', ['batch_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.create_index(op.f('ix_stock_movements_batch_id'), 'stock_movements', ['batch_id'], unique=False)
    op.drop_column('stock_movements', 'item_id')
    op.drop_column('items', 'expiry_date')
    op.drop_column('items', 'unit_cost')
    op.drop_column('items', 'quantity')
    op.create_table('batches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_code', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('batches_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('batches_location_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('batches_supplier_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('batches_pkey'))
    )
    op.create_index(op.f('ix_batches_location_id'), 'batches', ['location_id'], unique=False)
    op.create_index(op.f('ix_batches_item_id'), 'batches', ['item_id'], unique=False)
    op.create_index(op.f('ix_batches_batch_code'), 'batches', ['batch_code'], unique=True)
    # ### end Alembic commands ###
