"""add business_name to users

Revision ID: 82e5b89b9924
Revises: 53fdb8094134
Create Date: 2026-05-15 20:45:12.775616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e5b89b9924'
down_revision: Union[str, Sequence[str], None] = '53fdb8094134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('business_name', sa.String(length=160), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'business_name')
    # ### end Alembic commands ###
